name: PR Check

on: [pull_request]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          cd ./src
          python3 -m pip install --upgrade pip
          python3 -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          . .venv/bin/activate
          pip install pytest pytest-cov
          pytest
